### ISSUE TITLE
Custom login page

### ISSUE THREAD

**Issue by consult-kk** [bungle/lua-resty-session#102]
Hi,
This is not a defect/bug. But a request on some guidelines on how to customize the login page for an OP like PingFederate. 
How can I provide my own custom login page and perform auth and then redirect back
thanks,
KK

**Comment by bungle** [comment]
@consult-kk, thank you for the question, but I think this is outside of scope of this project. I am not sure if Ping Federate supports any customization. You can always do your own OIDC/SAML initial login page that asks e.g. email and that is then forwarded to idp login page. But to totally customize OP pages, you need to consult OP.
