### ISSUE TITLE
Support atomic read-update-write scenarios.

### ISSUE THREAD

**Issue by eriksunsol** [bungle/lua-resty-session#107]
This applies to `shm`, `redis` and `memcache` storage adapters which implement locking.

I'm assuming that the basic operations to read and write data for a single key in all three storage engines are atomic, which means that the purpose of locking here is not to protect those operations, but to protect more complex update scenarios.

### Current locking mechanism...

As far as I can see, locking as it is implemented here, in all three storage adapters, will protect against reading partially written data if `session:save()` is called multiple times with the argument `close = false`. And that's about it. This can be achieved without locking by simply not calling `session:save()` until updating the data is actually done. At some point `session:close()` should be called anyway to release the lock, at which point one might just as well call `session:save()` with `close = true`. Or the storage adapter could keep track of this internally and flush data to the underlying storage engine only once, e.g. when the session is closed.

### To the point...

What I'm looking for, and what seems to be missing, is the ability to retrieve the lock when data is read and not release it, even for a short while, until `session:save()` is called with `close = true` or `session:close()` is called.

If this is possible with the current API, I would appreciate an example showing how to set it up. If not, please read on!

Having the ability to acquire the lock on read and keep it util the session object is closed doesn't mean that this should occur every time data is read, but only after it has been determined that an update is needed. That's to ensure that we get performance most of the time, assuming that updates occur relatively seldom while the session is accessed read-only most of the time. N.B. that if writing only occurs at the end, there is no need to lock during a normal read.

To highlight the importance of supporting atomic read-update-write scenarios, there are other dependent libraries that do not work as expected in cases where locking is needed because they (falsely?) assume that the locking mechanism protects against inconsistencies due to concurrent updates. I may be a bit biased as I'm the author, but [here's an example where __lua-resty-openidc__ fails](https://github.com/zmartzone/lua-resty-openidc/issues/334) with some deeper explanations as to why the locking does not work and what would be required to make it work.

**Comment by bungle** [comment]
Where do you see that `:start` or `.start` does not hold lock until `:close` or `:save` is called when locking is enabled?

**Comment by bungle** [comment]
Do you mean the problem lies here:
https://github.com/bungle/lua-resty-session/blob/master/lib/resty/session.lua#L611

AND

https://github.com/bungle/lua-resty-session/blob/master/lib/resty/session.lua#L625

1. open reads data and tries to acquire lock so that it does not return until another request has released the lock, the lock is released right after reading
2. start call is made and lock is acquired

So is what you want that the lock is held between 1. and 2.?

**Comment by bungle** [comment]
It means that single process needs to make two  (or more) simultaneous requests:

e.g.:

a: open, lock
b: open, wait
a: release
b: lock, release, lock
a: wait
b: save
a: has stale data?

Is this what you are after?

**Comment by bungle** [comment]
Isn't it simple to fix by just lock it right when you call `:start`? and not release until `:close` or `:save`? What about the scenario where there is no session, but concurrent requests? Should it still block others? How could we?

**Comment by bungle** [comment]
There is also a `regenerate` strategy that you may want to look when having a lot of concurrency: https://github.com/bungle/lua-resty-session#pluggable-session-strategies

**Comment by eriksunsol** [comment]
> https://github.com/bungle/lua-resty-session/issues/107#issuecomment-676695888
> So is what you want that the lock is held between 1. and 2.?

Correct.

> https://github.com/bungle/lua-resty-session/issues/107#issuecomment-676697682
> Is this what you are after?

Yes, this is one scenario. There are a few permutations that could occur on the same theme, and since the exact sequence of events is up to a scheduler which we cannot control, all of them need to be taken care of.

> Isn't it simple to fix by just lock it right when you call :start? and not release until :close or :save (or timeout)? What about the scenario where there is no session, but concurrent requests? Should it still block others? How could we?

Yes, that could be a simple fix provided one can also make the call to `start` re-read the session data. Ideally there would be two recommended use scenarios, one read-only and one read-write, where the read-only only involves the `open` call doesn't allow `save` and doesn't lock, and the read-write involves `start`, `save` and possibly `close` and locks the session before doing anything else. The reason why `start` needs to re-read is that you'd want to be able to first run the read-only scenario and based on what's in the data decide to switch to read-write, e.g. due to an expired token. But then another thread may have changed the data before the switch could be made so re-reading is essential to make sure we're not working on stale data. Another option is to simply not allow switching from read-only to read-write and instead require that you acquire a new session object.

To be clear I don't think any of this makes any sense with cookie storage because you would need to use some other storage for the locks anyway...

I think you have to assume that there are no concurrent requests before the session has been established. Before that point locking will be pointless (but also harmless) as the session Id has not yet been shared in a way (i.e. a session id cookie) which would enable concurrent requests to use the same session Id. There is no way around that, just as you point out.

> The iframes and regenerate is nice example though (but who uses iframes anymore).

Haha, good point. The iframes could be replaced with any other resource that the browser would throw out concurrent requests for, e.g. images, scripts, etc. Let's say you do not want images to be accessible without being logged in, then that might serve as a more realistic example.

**Comment by eriksunsol** [comment]
> But if you absolutely want to modify and have modification serialized, you will need bigger locks for sure. In a real-world, I rarely see a need for that, but I still agree that making :start not to release even for a microsecond is a good fix.

After the lengthy elaboration above (sorry about that) and some careful consideration, I agree that fixing `start` so it does not release the lock will most likely be sufficient. Then users of __lua-resty-session__ can implement whatever higher level locking scheme is required by the application. And it seems like a non-breaking change. I could suggest a more rigid approach, but that would be a whole new API so it's not a realistic option for __lua-resty-session__ as of now. I would suggest though that the README.md file is also updated with a note explaining what the locking does and the dangers of calling `start` on an already `open` session. I thing that will be a good balance between rigor and flexibility.

**Comment by bungle** [comment]
> ha, good point. The iframes could be replaced with any other resource that the browser would throw out concurrent requests for, e.g. images, scripts, etc.

The point that I wanted to make is that `browser` loads a page usually `html`. At this point there is no concurrency. After loading that html there can be links that then can be loaded concurrently. Session writing in my opinion should happen on that load of `html` that is not concurrent.

The exception these days seem to be XMLHttpRequests. But even with that, you usually need at least 1 request (that is not concurrent) to start the app. Have you btw. tried that `set $session_strategy regenerate;`?

What is a more rigid approach? I am interested to hear about it. But if we make the fix that we agree don't we then have:
1. open -> waits for lock to be released, locks, reads data, releases lock
2. start -> waits for lock to be released, locks, reads data (user needs to call `save` or `close`)
