### ISSUE TITLE
Session cookie is not invalid after logout

### ISSUE THREAD

**Issue by emrulhaikal** [bungle/lua-resty-session#108]
Describe the bug
This comes from pentest team, on of the session invalid scenario where we can use session cookie on different browser and machine.

Steps to Reproduce
1) Login in one browser (Chrome) or machine, click on inspect -> Cookies and copy the value of 'session' cookie.
2) Open another browser(e.g Firefox) or machine, import previous exported cookie, can directly access application without a login.
3) Logout in first browser/machine successfully.
4) Second browser/machine can still continue use the cookies(imported in step 2).

Expected behavior
After logout in first browser/machine, should invalid the session cookie in and second browser/machine shouldn't able to use the old cookies .

**Comment by bungle** [comment]
What storage are you using for cookie? If you use cookie storage, there is no way to do that, unless you start to maintain revocation list (e.g. list of signatures that cannot be used). But then again that needs to be stored somewhere.
