### ISSUE TITLE
Infinite session lifetime

### ISSUE THREAD

**Issue by SMakhrov** [bungle/lua-resty-session#109]
Good day!

Could you tell how can I set infinite session lifetime?
As I have found at code the default value is 3600 = 60m. But how to set infinite value?

**Comment by bungle** [comment]
By definition sessions are infinite as long as you use it.

**Comment by bungle** [comment]
Google says: (10^307) seconds = 3.16887646 × 10^299 years. I bet no-one uses this library by then.

**Comment by bungle** [comment]
4.0.0 you an turn things off by setting e.g. *_timeout=0
