### ISSUE TITLE
Error loading module resty.session.ciphers.aes

### ISSUE THREAD

**Issue by KwadwoObeng** [bungle/lua-resty-session#120]
I haven't seen this issue anywhere else before. Except one at https://stackoverflow.com/questions/60756112/runtime-error-usr-local-share-lua-5-1-resty-session-lua183-loop-or-previous which was unanswered.Do you guys have any idea what is causing this

lua entry thread aborted: runtime error: /usr/local/share/lua/5.3/resty/session.lua:70: loop or previous error loading module 'resty.session.ciphers.aes'
stack traceback:
coroutine 0:
        [C]: in function 'require'
        /usr/local/share/lua/5.3/resty/session.lua:70: in function 'prequire'
        /usr/local/share/lua/5.3/resty/session.lua:512: in function 'new'
        /usr/local/share/lua/5.3/resty/session.lua:575: in function 'open'
        /usr/local/share/lua/5.3/resty/session.lua:615: in function 'start'
        /usr/local/share/lua/5.3/resty/openidc.lua:1393: in function 'authenticate'

**Comment by zariwal** [comment]
Yes also having the same issue, please provide some guidance on how to fix it.

**Comment by KwadwoObeng** [comment]
@zariwal If you figure out how to fix it kindly share it here

**Comment by zariwal** [comment]
@KwadwoObeng for now i changed the cipher setting in session.lua to none and after that its working. But not sure what should be the proper fix.

**Comment by bungle** [comment]
You will need this:
https://github.com/openresty/lua-resty-string

**Comment by zariwal** [comment]
@bungle thanks, its working after that.

**Comment by zariwal** [comment]
@bungle I am trying to use the storage adapter shm aka Lua Shared Dictionary. I have configured following in my nginx configuration. 

http block
lua_shared_dict sessions 10m;

location block
set $session_storage shm;

But i still the see the data in session storage. Any suggestions please?

Also is there a way I can decrypt the session data? please let me know.
