### ISSUE TITLE
Feature request: Support for Redis Sentinel

### ISSUE THREAD

**Issue by thorstenfleischmann** [bungle/lua-resty-session#122]
Currently lua-resty-session only supports redis cluster. Redis cluster has no failover mechanisms.

Using [lua-resty-redis-connector](https://github.com/ledgetech/lua-resty-redis-connector) might be an easy way to enable support for Redis Sentinel.

I did some very basic tests by copying the redis storage adapter and alter connect so that it utilizes "lua-resty-redis-connector". This seems to work fine. 

```
function storage:connect()
    local connect_url = "sentinel://" .. self.auth .. "@" .. self.sentinel_master .. ":m/" .. self.database

    local redis, err = self.rc:connect({
        url = connect_url,
        sentinels = {
            { host = self.host, port = self.sentinel_port },
        },
    })

    if not redis then
        return nil, err
    end

    self.redis = redis

    return redis, err
end 
```

**Comment by bungle** [comment]
@thorstenfleischmann interesting, yes, sentinel support would be nice to have too.

**Comment by edmundofreitas** [comment]
Hey! Do you have any news about this feature?

**Comment by bungle** [comment]
Redis sentinels are supported with 4.0.0
