### ISSUE TITLE
Multiple cookie domains support in lua-resty-session

### ISSUE THREAD

**Issue by Subbu3992** [bungle/lua-resty-session#130]
**Open Question:**

1. Currently does lua-resty-session supports multiple cookie domains, if so how?

**Actual Need:**

We are using common kong gateway for multiple applications, that are in different domain [sample.ex.com, asample.xe.com].

Session values configured through KONG_NGINX_CONFIG_FILE as below 

set $session_cookie_domain ex.com; [only one domain input allowed and could not use patterns as well]

in the above case kong could not serve other application  asample.xe.com and errors out with "request to the redirect_uri_path but there's no session state found" after OIDC authentication.

Is it feasible to have multiple cookie domains in lua-resty-session?

**Comment by bungle** [comment]
@Subbu3992, sure, you can configure the library dynamically in Lua code. You don't need to use Nginx variables for that.

```lua
local session = require "resty.session".open { cookie = { domain = "a.com" } }
```

**Comment by bungle** [comment]
This is how Kong session plugin does it:
https://github.com/Kong/kong-plugin-session/blob/master/kong/plugins/session/session.lua#L12-L43

**Comment by bungle** [comment]
If you mean can you send cookie that browser sends to multiple different domains, the answer is that you cannot. But that is by cookie specification.
