### ISSUE TITLE
redis and session id 

### ISSUE THREAD

**Issue by matth-c3** [bungle/lua-resty-session#132]
Hello, 

Im using `resty.openidc` and they provide an options `lifecycle` that allow us to manipulate the session in 4 lifecycle options :

```
lifecycle = {
    on_created = handle_created,
    on_authenticated = handle_authenticated,
    on_regenerated = handle_regenerated
    on_logout = handle_logout
}
```

`handle_created`, `handle_authenticated`, `handle_regenerated` and `handle_logout` are methods that take the session as argument.

Example: 

```
local _M = {}
local cjson = require("cjson")


function _M.on_created(session)
    -- ngx.say("jere")

    ngx.log(ngx.INFO, "on_created is -----------> :    --->", cjson.encode({session = session.id }))

    -- ngx.say() 
end

return _M
```

I would like to keep track of the sessions id of each user but Im not sure how to get it. As indicated in the documentation, `by default it is 16 bytes long (raw binary bytes)`. 

How can I convert it to a string ? Is this the appropriate way to get the session id ? 

To be clear, I would like to get the same id than in redis (example `P-WhIe1pYvzPGio8oQjDpw` ) : 

```
127.0.0.1:6379> KEYS *
 1) "users:sessions:P-WhIe1pYvzPGio8oQjDpw"
 ```

thanks

**Comment by bungle** [comment]
Yes, this is a good feature request. I will look at implementing it. Perhaps we need to add something like `session.subject = "user-x" that then get's stored nicely in databases, so that you could delete sessions by user, or limit that user can have just single session at time.

**Comment by bungle** [comment]
Relates to #131

**Comment by some0ne2** [comment]
@bungle Any update onto this? Would require such a feature too.
Is there any workaround how to get to the same id as stored inside redis, so I can interact with the redis data directly?

**Comment by some0ne2** [comment]
Bump this, please don't let this library die.

**Comment by some0ne2** [comment]
Has anybody a hint for this problem?

**Comment by bungle** [comment]
The 4.0.0 has `store_metadata` option that enables collecting the sessions per user. It is to be used with `:set_subject("jere")` and perhaps `:set_audience("my-audience")` . Audience can also be set on config level.
