### ISSUE TITLE
Break down the session variables into smaller parts

### ISSUE THREAD

**Issue by anishnagaraj** [bungle/lua-resty-session#133]
Is there a way to break down the session variables stored as cookies into smaller parts? Is this configurable?

I need this because sometime the cookies are too big and we get an 431 Http error code back.

**Comment by bungle** [comment]
Yes, and it is by default:
https://github.com/bungle/lua-resty-session#string-sessioncookiemaxsize

**Comment by bungle** [comment]
You can also zlib compress your large cookie:
https://github.com/bungle/lua-resty-session#pluggable-compressors
