### ISSUE TITLE
Inconsistency in session.start() return values

### ISSUE THREAD

**Issue by dmitrysleptsov** [bungle/lua-resty-session#150]
Hi
Thanks for this great library. I noticed some inconsistency in return value for session.start() method. According to docs, it should return `session, present, reason`. But looking at the code [here](https://github.com/bungle/lua-resty-session/blob/master/lib/resty/session.lua#L628), [here](https://github.com/bungle/lua-resty-session/blob/master/lib/resty/session.lua#L637), [here](https://github.com/bungle/lua-resty-session/blob/master/lib/resty/session.lua#L646) and [here](https://github.com/bungle/lua-resty-session/blob/master/lib/resty/session.lua#L652) we can see, that only two values are returned. It makes it harder to debug, because error can appear in different places (in 2nd or 3rd) argument.

I can prepare a PR to fix it if you don't mind.

**Comment by bungle** [comment]
The 4.0.0 should be using consistently `val, err, ... = function()`
