### ISSUE TITLE
Session `audience` and `subject` semantics clarifications

### ISSUE THREAD

**Issue by pankgeorg** [bungle/lua-resty-session#160]
How do these differ from normal variables? What is the intended use case? Are these "just" a namespace?

**Comment by bungle** [comment]
The audience is essentially a namespace for data. Subject is an identifier for the user.

Audiences allow so called global sessions. That is, you can specify timeouts etc. that are applied to all services (audiences) but you still have to authenticate to each separately. Also session:logout signs you off from just current audience, and session:destroy from all services. This way you can have just one session and one session cookie across several services.

Audiences and subjects are also used to collect metadata (strore_metadata=true), e.g. how many sessions a single subject has to audience. This allows us to implement (in a future) things like n-number of active sessions per subject per audience.

You can use the library just fine without ever thinking about audiences and subjects. These requirements come from real world use cases. We might add another layer ”scopes” in a future. The terminology comes pretty much from OpenID Connect world, see aud, sub and scopes claims.

**Comment by pankgeorg** [comment]
Thanks for the clarifications!
