### ISSUE TITLE
Question about `rolling_timeout`

### ISSUE THREAD

**Issue by alohec** [bungle/lua-resty-session#166]
The description of the `rolling_timeout` param contains the following:
```
Rolling timeout specifies how long the session can be used until it needs to be renewed,
```
What exactly is meant by "renewed" in this context? Does it simply mean that `session:refresh` is called?

**Comment by bungle** [comment]
For example, if you have rolling_timeout set to 3600 seconds (1 hour). The cookie will function for 1 hour. Session:refresh takes care of either calling touch (manipulates just cookie, not the possible server side data or its expiry) or save (creates new row in db and sends s new cookie and expires the old one within 10 secs by default). Calling session.start will also take care of it. And any call to save will also set a new cookie with another rolling_timeout of expiry.

So yes, you got it basically right.

**Comment by bungle** [comment]
session.start = open + refresh
session:refresh = touch or save
touch = just updates cookies idling offset
save = creates new session with fresh timeouts (the original creation time is carried over if there was already existing session), and possible existing session is set to expire and new cookie will be set.

**Comment by bungle** [comment]
@alohec, let me know if you have further questions.
