### ISSUE TITLE
session:regenerate(true) failing after starting session

### ISSUE THREAD

**Issue by hulu1522** [bungle/lua-resty-session#19]
I am checking for valid sessions and in some situations new credentials are provided.  In this situation I am choosing to regenerate the session instead of destroying and creating a new one (my understanding was that regenerate already did that).  It is failing to regenerate though.

Here is the stack trace:
```
2015/10/15 21:15:14 [error] 25755#0: *980 lua entry thread aborted: runtime error: /usr/share/luajit/share/lua/5.1/resty/session.lua:101: attempt to call field 'destroy' (a nil value)
stack traceback:
coroutine 0:
        /usr/share/luajit/share/lua/5.1/resty/session.lua: in function 'regenerate'
        /usr/share/luajit/share/lua/5.1/resty/session.lua:282: in function 'regenerate'
        /etc/nginx/scripts/combined.lua:61: in function </etc/nginx/scripts/combined.lua:1>, client: 10.129.253.131, server: , request: "GET /?accesskey=dd37a772-a0b3-49b9-bd7f-2ce217427f15 HTTP/1.1", host: "10.129.22.47", referrer: "http://localhost:8080/"
```

Any help would be appreciated.  Thanks.

**Comment by bungle** [comment]
Thanks a lot for this report. I will check what's wrong.

**Comment by bungle** [comment]
This is now fixed and a new version is released. Thanks for reporting.
