### ISSUE TITLE
session id generator using JWT as id

### ISSUE THREAD

**Issue by mingfang** [bungle/lua-resty-session#21]
Is there an example of how to write a session id generator?
I want to create a JWT as the session id.

**Comment by bungle** [comment]
Interesting, it is on the todo list. Maybe if I create the first one you can contribute JWT?

**Comment by mingfang** [comment]
Great. 
I must declare that I'm by no means a Lua expert. But I will try.

**Comment by bungle** [comment]
I let you know when the ground work is done.

**Comment by bungle** [comment]
@mingfang, I'm not sure if this is interesting to you anymore, but I just released version 2.12 that has pluggable session identifier generators possible. If you wish to contribute, please do so. The default one is here: https://github.com/bungle/lua-resty-session/blob/master/lib/resty/session/identifiers/random.lua
