### ISSUE TITLE
Setting session expiration when using Redis?

### ISSUE THREAD

**Issue by siasia** [bungle/lua-resty-session#24]
I see there are these variables when using cookie storage 
```
set $session_cookie_renew      600;
set $session_cookie_lifetime   3600;
```

Are there analogous ones when using storage like Redis? How can I set the number of seconds after which an inactive session expires? and how long is the session life extended when session is accessed? 

Thanks.

**Comment by bungle** [comment]
It uses the same config, as you can see here:
https://github.com/bungle/lua-resty-session/blob/master/lib/resty/session.lua#L242

While using Redis, you are still sending the cookie as well, but the session data is not stored on client cookie, only the session identifier.

**Comment by bungle** [comment]
Session life is extended to $session_cookie_lifetime (aka to full extend). The renew is only there so that we don't autorenew, until the lifetime is below say 600 secs. But whenever you call `session:save` it will automatically renew the lifetime as well.

**Comment by siasia** [comment]
Thank you. Closing the question.
