### ISSUE TITLE
non-persistent cookies seem to be invalid after cookie lifetime elapses

### ISSUE THREAD

**Issue by consultantRR** [bungle/lua-resty-session#25]
My understanding from the documentation was that, in cases where `session.cookie.persistent = off`, that  `$session_cookie_lifetime` is ignored for that cookie. Indeed when I start a session with `session.cookie.persistent = off` and`set $session_cookie_lifetime   600;` the browser shows that the cookie is a `Session` cookie and does not show an expiry time/date.

However, in testing, resty-session seems to consider that cookie invalid after 600 seconds.

Have I misread the documentation, or is this an issue in resty-session?

**Comment by consultantRR** [comment]
Here is a more specific example:

Config;

```
        set $session_check_ssi off;
        set $session_cookie_renew      30;
        set $session_cookie_lifetime   60;
```

and

```
    location / {
            content_by_lua_block {

                  local test_session = require "resty.session".new()
                  test_session.name = "testcookie"
                  test_session.cookie.persistent = off
                  test_session.cookie.domain = ngx.var.host
                  test_session:open()

                  test_session:start()
                  test_session.data.foo = "bar"
                  test_session:save()

                  if test_session.present then
                    ngx.say("present")
                  else
                    ngx.say("not present")
                  end

                  ngx.status = 200
                  
            }
        }
```


Test #1:

```
# curl -v localhost
* Rebuilt URL to: localhost/
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.40.0
> Host: localhost
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: openresty
< Date: Thu, 07 Apr 2016 21:32:54 GMT
< Content-Type: application/octet-stream
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: testcookie=aBnLaO61j-vjzxljDg2LlA..|1460064834|l2ivtSwcWxTIiCnXYISMUA..|Bx5bR6GS2QzKoeK3mUPO8t96L0w.; Path=/; HttpOnly
< 
not present
* Connection #0 to host localhost left intact
```

Test #2, using cookie from above:

```
# curl -v --cookie "testcookie=aBnLaO61j-vjzxljDg2LlA..|1460064834|l2ivtSwcWxTIiCnXYISMUA..|Bx5bR6GS2QzKoeK3mUPO8t96L0w." localhost
* Rebuilt URL to: localhost/
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.40.0
> Host: localhost
> Accept: */*
> Cookie: testcookie=aBnLaO61j-vjzxljDg2LlA..|1460064834|l2ivtSwcWxTIiCnXYISMUA..|Bx5bR6GS2QzKoeK3mUPO8t96L0w.
> 
< HTTP/1.1 200 OK
< Server: openresty
< Date: Thu, 07 Apr 2016 21:33:11 GMT
< Content-Type: application/octet-stream
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: testcookie=aBnLaO61j-vjzxljDg2LlA..|1460064851|GmNtCFAfMTpkOe2qx8YXMA..|OCaFOfreMJAONCPvwyyI6nu3Uxk.; Path=/; HttpOnly
< 
present
* Connection #0 to host localhost left intact
```

Test #3, same as #2, but one minute later:

```
# curl -v --cookie "testcookie=aBnLaO61j-vjzxljDg2LlA..|1460064834|l2ivtSwcWxTIiCnXYISMUA..|Bx5bR6GS2QzKoeK3mUPO8t96L0w." localhost
* Rebuilt URL to: localhost/
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.40.0
> Host: localhost
> Accept: */*
> Cookie: testcookie=aBnLaO61j-vjzxljDg2LlA..|1460064834|l2ivtSwcWxTIiCnXYISMUA..|Bx5bR6GS2QzKoeK3mUPO8t96L0w.
> 
< HTTP/1.1 200 OK
< Server: openresty
< Date: Thu, 07 Apr 2016 21:33:59 GMT
< Content-Type: application/octet-stream
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: testcookie=qyMxdyOVlyACTZl3mXgQXw..|1460064899|qFiWOTjhrSy8ayyM-lT-6w..|j00VbJWddoNoNmnwHdlhaSESfn0.; Path=/; HttpOnly
< 
not present
* Connection #0 to host localhost left intact
```

**Comment by bungle** [comment]
1. When persistent is off the cookie has no lifetime, aka cookie will be deleted when browser is closed.
2. We still check the lifetime on server
3. The cookie itself has lifetime coded in cookie data
4. Only persistent cookies set the expire headers (still the timestamp is also on cookie data)

If you don't want non persistent cookies to expire, then set the lifetime to something like 10 years. But this is problematic when using server side storages as more and more resources are needed to store those sessions.

I think in most frameworks session expiration is handles similarly.

**Comment by bungle** [comment]
So more specifically cookie lifetime is the time how long the server accepts the cookie (on renew a new cookie will be sent with a new lifetime). It is aldo used as cookie expires headers on persistent cookies so the browser can also decide to not send it anymore. Still we are talking about sessions, so the final decision is on the server.

**Comment by bungle** [comment]
It is possible that we add something like cookie.lifetime = 'infinite' or something, but in general I think it is not good idea to have "forever" cookies. If you want to have a "remember me" cookie, I do suggest to have it separate from session cookie. E.g. session using non persistent relatively short lived lifetime (like the default 600), and remember me cookie using persistent 2 weeks or something cookie.

**Comment by bungle** [comment]
You can use:
`2147483648`

as `session.cookie.lifetime`.

I will close this now. There is no better solution.
