### ISSUE TITLE
Is this a typo?

### ISSUE THREAD

**Issue by pronan** [bungle/lua-resty-session#30]
line 38 of  [`lua-resty-session/lib/resty/session/ciphers/aes.lua`:](https://github.com/bungle/lua-resty-session/blob/master/lib/resty/session/ciphers/aes.lua) 
`size   = CIPHER_MODES[a.size or defaults.size]   or 256,`

should be:
`size   = CIPHER_SIZES[a.size or defaults.size]   or 256,`

**Comment by bungle** [comment]
@pronan, Yes it is, thanks for reporting this. It is already fixed in the master, and I will release a new version today.

**Comment by bungle** [comment]
This is now fixed and a new version is released. Thanks again.
