### ISSUE TITLE
support for chunked cookies

### ISSUE THREAD

**Issue by zandbelt** [bungle/lua-resty-session#35]
Using the default cookie storage it may happen that the size of the cookie runs over browser limits when a lot of data is stored in the session. Adding support for chunked cookies would mitigate this somewhat. See: https://github.com/pingidentity/lua-resty-openidc/issues/33

**Comment by bungle** [comment]
@zandbelt, Thanks. I saw that report. We should consider adding this support to `lua-resty-session`. Do you happen to know if there is any "standard" of how this should be handled?

**Comment by zandbelt** [comment]
I don't think there's a real standard; it doesn't really need one because its all "internal"; the process would be:
1. determine that the cookie size is too large to put in a single cookie (e.g. size > MAX bytes)
2. determine the number of cookies that should be used (e.g. n = size / MAX)
3. write a cookie that contains the number of chunks (e.g. Set-Cookie: session_number=<n>)
4. write the cookies that contain the content (e.g. Set-Cookie: session_1=..., Set-Cookie: session_2=..., Set-Cookie: session_<n>=...)

On retrieval one would check whether a cookie named `session_number` exists and would try read that many cookies whilst concatenating the content, otherwise fallback to the current behavior.

For an idea of the effort, see:
https://github.com/pingidentity/mod_auth_openidc/commit/5b6bb062b2d8c48d629ad7325d8bac689e0c9cd5

There's still a limitation in the maximum size of the (single) "Cookie" header that the browser will actually manage to send, but that is known to be much larger (typically at least 81920), see:
http://browsercookielimits.squawky.net/

**Comment by bungle** [comment]
Okay. I can think about implementing this. Thank you. I already started looking at it.

**Comment by bungle** [comment]
@zandbelt,

The first try to do this is implemented in these commits:
https://github.com/bungle/lua-resty-session/commit/b641e4b65079f64463063811e3d42b049eba898c
https://github.com/bungle/lua-resty-session/commit/99407c9919a79f69b6483172870d489acc4b2ec3
https://github.com/bungle/lua-resty-session/commit/3494b1684ee02d6f1328be40593d53794b6df2a4

BEWARE!

I just wrote the code, but I have not run it. That means that there could be some nasty bugs. Also in this version the `data` part of the cookie is limited to fixed 4000 chars in each chunk (we can add configuration later), to make room for name and flags.

I don't have time to test this thoroughly right now. But all the feedback is welcomed.

**Comment by bungle** [comment]
I made some obvious fixes after the comment above.

**Comment by bungle** [comment]
@zandbelt,

Okay, it got some nasty bugs, but those are resolved now.

Can you please try it out and report back to me if it works as expected. 

Note: please also adjust your Nginx config as needed, e.g. to accept larger cookies, you may need to add something like this in `nginx.conf`:

```nginx
large_client_header_buffers 4 16k;
```

**Comment by bungle** [comment]
This is now released as a part of 2.15 release.
