### ISSUE TITLE
Hello World example fails on Debian 9

### ISSUE THREAD

**Issue by erl987** [bungle/lua-resty-session#39]
I have installed nginx on a clean Debian 9 machine and got initially the following error:

2017/07/05 20:59:03 [error] 7838#7838: *1 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/resty/session.lua:20: module 'resty.random' not found:
        no field package.preload['resty.random']
        no file './resty/random.lua'
        no file '/usr/share/luajit-2.0.4/resty/random.lua'
        no file '/usr/local/share/lua/5.1/resty/random.lua'
        no file '/usr/local/share/lua/5.1/resty/random/init.lua'
        no file '/usr/share/lua/5.1/resty/random.lua'
        no file '/usr/share/lua/5.1/resty/random/init.lua'
        no file './resty/random.so'
        no file '/usr/local/lib/lua/5.1/resty/random.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.1/resty/random.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './resty.so'
        no file '/usr/local/lib/lua/5.1/resty.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.1/resty.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
        [C]: in function 'require'
        content_by_lua(default:17):2: in function <content_by_lua(default:17):1>, client: 127.0.0.1, server: localhost, request: "GET /start HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/"

Steps to reproduce:
1. Clean Debian 9 machine
2. sudo apt-get install nginx-extras
3. sudo apt-get install luarocks
4. sudo luarocks install lua-resty-session
5. replace the file /etc/nginx/sites-available/default by the content of the "Hello World" example (only the "server"-content)

6. sudo systemctl restart nginx-extras
7. browse to http://localhost:8080
8. clicking on "Start the test!"
9. 500 Internal Server Error appears
10. /var/log/nginx/error.log shows the error message shown above.

By installing:
1. sudo luarocks install lua-resty-string
2. sudo luarocks install lua-cjson

this error can be resolved.

But now the same trial delivers the following error in /var/log/nginx/error.log:

2017/07/05 21:15:20 [error] 12961#12961: *1 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/resty/aes.lua:170: /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2: undefined symbol: EVP_CIPHER_CTX_init
stack traceback:
coroutine 0:
        [C]: in function '__index'
        /usr/local/share/lua/5.1/resty/aes.lua:170: in function 'new'
        /usr/local/share/lua/5.1/resty/session/ciphers/aes.lua:46: in function 'encrypt'
        /usr/local/share/lua/5.1/resty/session.lua:156: in function 'save'
        /usr/local/share/lua/5.1/resty/session.lua:344: in function 'start'
        content_by_lua(default:17):2: in function <content_by_lua(default:17):1>, client: 127.0.0.1, server: localhost, request: "GET /start HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/"

Obviously this is a linker error for the libssl-dev. Several trials, for example installing

sudo apt-get install libssl-dev

did not help.

So it appears that the documentation (or the package itself) are missing important dependencies and some linking to openssl is not working out of the box on Debian 9?

**Comment by zandbelt** [comment]
The README.md does mention that it takes OpenResty as a starting point. Perhaps worth installing that from: https://openresty.org/en/linux-packages.html

**Comment by bungle** [comment]
OpenResty is quickest path. You could do it by hand, but this is probably not the repository to talk about that. OpenResty is an Nginx distribution that comes with several additional Nginx modules. Most interesting here is lua-nginx-module. It also comes with several Lua libraries that lua-resty-session depends on.

**Comment by erl987** [comment]
Ok, thanks. That actually works, although it is not ideal for me that OpenResty is not packaged in Debian.

For me the difficulty to work with lua-resty-ression out of the box was not clear from reading the documentation.

**Comment by bungle** [comment]
@erl987,

OpenResty is packaged for Debian, see just here:
https://openresty.org/en/linux-packages.html

**Comment by erl987** [comment]
Ah ok, thanks.

**Comment by bungle** [comment]
I think this can be closed. Please reopen if you feel there is something `lua-resty-session` needs to implement/fix.
