### ISSUE TITLE
Setting a session_secret on hostnames containing hyphens fails.

### ISSUE THREAD

**Issue by Yermo** [bungle/lua-resty-session#42]
Using the example from https://github.com/bungle/lua-resty-session#hello-world-with-lua-resty-session on a site where there is a hyphen in the host name fails.

To reproduce set up a test site such as `test-site.mydomain.com` 

Set a session secret explicitly:

`set $session_secret 623q4hR325t36VsCD3g567922IC0073T;`

And try the example.

**Comment by bungle** [comment]
thanks, I will look at this soon.

**Comment by bungle** [comment]
@Yermo, can you give me a full example (full config, and version info + the code you tried), and what does it mean, that it doesn't work (always anonymous)?

**Comment by Yermo** [comment]
Yes, always anonymous.

Ubuntu 16.04.2 LTS
openresty 1.11.2.3-4~xenial1

nginx.conf:
```
# the openresty service script apparently assumes the pid file is in this location.

pid logs/nginx.pid;

events {
    worker_connections  1024;
}

http {

        # Basic Settings

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;

        include       mime.types;
        default_type  application/octet-stream;

        # Logging Settings

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log debug;

        # Gzip Settings
        gzip on;
        gzip_disable "msie6";

        # LUA config

        lua_package_path "/usr/local/openresty/site/lualib/nginx-jwt/?.lua;/usr/local/openresty/site/lualib/resty/?.lua;;";

        include /usr/local/openresty/nginx/conf/sites-enabled/*;
}
```

test site config:

```
# Tile Server Docker Instance Proxy
#
# @see https://github.com/bungle/lua-resty-session

server {

	listen tileserver-mbymc.yml.com:80; 
        server_name  tileserver-mbymc.yml.com;
        default_type text/html;

#	set $session_secret 768e80f79de3629d5a88761305ba4f64f041b73429a69042c12dc7e4477f0486;

	set $session_secret 623q4hR325t36VsCD3g567922IC0073T;


        location / {
            content_by_lua '
                ngx.say("<html><body><a href=/start>Start the test</a>!</body></html>")
            ';
        }
        location /start {
            content_by_lua '
                local session = require "resty.session".start()
                session.data.name = "OpenResty Fan"
                session:save()
                ngx.say("<html><body>Session started. ",
                        "<a href=/test>Check if it is working</a>!</body></html>")
            ';
        }
        location /test {
            content_by_lua '
                local session = require "resty.session".open()
                ngx.say("<html><body>Session was started by <strong>",
                        session.data.name or "Anonymous",
                        "</strong>! <a href=/destroy>Destroy the session</a>.</body></html>")
            ';
        }
        location /destroy {
            content_by_lua '
                local session = require "resty.session".start()
                session:destroy()
                ngx.say("<html><body>Session was destroyed. ",
                        "<a href=/check>Is it really so</a>?</body></html>")
            ';
        }
        location /check {
            content_by_lua '
                local session = require "resty.session".open()
                ngx.say("<html><body>Session was really destroyed, you are known as ",
                        "<strong>",
                        session.data.name or "Anonymous",
                        "</strong>! <a href=/>Start again</a>.</body></html>")
            ';
        }
    } 
```

This does not work. The session is never established. It says "anonymous". However, if I change the servername and listen line to test.yml.com it works. Both tileserver-mbymc.yml.com and test.yml.com resolve to the same IP address on my local network. 

I have just reproduced it here again. Hopefully it is not a case of me doing something very stupid in my test setup here.

**Comment by bungle** [comment]
@Yermo, thanks, this is definitely good information. I will look if I can reproduce this. I looked the code shortly, and I couldn't find anything that edeals with dashes, but I try again, harder.

**Comment by bungle** [comment]
@Yermo just to make sure, your Nginx will not load any other configs? This is all? E.g. in sites there is no other configs? Especially those that do `set $session_...`?

**Comment by bungle** [comment]
Not sure about yout Lua package path, it looks strange:

```
lua_package_path "/usr/local/openresty/site/lualib/nginx-jwt/?.lua;/usr/local/openresty/site/lualib/resty/?.lua;;"```
```

Shouldn't that just be:

```
lua_package_path "/usr/local/openresty/site/lualib/?.lua;;"
```

**Comment by Yermo** [comment]
@bungle Hmm. So set is global to the config? I did not know that. I do in fact set $session in each config I load but I set it to the same value. 

I have repeated my experiment after having removed all other sites so there is only the config I set above with the same result. There is still the possibility that I am doing something stupid since I am very new to openresty/lua.

**Comment by Yermo** [comment]
I may have some issue with my openresty install with regard to the paths. nginx-jwt is not available through opm so I had to copy it in by hand.

**Comment by bungle** [comment]
@Yermo, thanks again, I try to make minimal test case out of your configs.

**Comment by Yermo** [comment]
Thank you for taking a look at it. It may be that I am doing something wrong in my setup.

I have been noticing some odd behavior in my setup here so there may yet be something else involved.

**Comment by Yermo** [comment]
I think this issue can be closed. 

From what I can tell there was some conflict in the dependencies between the nginx-jwt module and lua-resty-session. So there is no problem with with lua-resty-session. It was my error.

There's no opm module for nginx-jwt so I had copied it in by hand and set the path manually. It was your comment about the path that let me to realize that there were some dependency conflicts.

Removing nginx-jwt and installing another jwt library lua-resty-jwt via opm (and updating the path as you suggested) resolved this issue.

I sincerely apologize for the wild goose chase.

**Comment by bungle** [comment]
@Yermo good to know. I had some hard time to reproduce this. Good to know that it can be considered solved. You can always make your own package out of nginx-jwt and release it on opm if you wish. OPMs are always prefixed with the provider so there can be multiple nginx-jwt's.

**Comment by Yermo** [comment]
I feel bad that it was a bad bug report. Thank you for taking the time to look into it and respond.

**Comment by bungle** [comment]
@Yermo, no reason to feel bad! Good that you reported it, and eventually it got solved.
