### ISSUE TITLE
feature-request: ability to use hostnames for memcache server

### ISSUE THREAD

**Issue by idar** [bungle/lua-resty-session#45]
It would be great if it was possible to use hostnames for memcache server and not only ip.

**Comment by idar** [comment]
Why can't nginx use host resolv.conf file ????

**Comment by bungle** [comment]
@idar I think you already figured this out? Yes Nginx doesn't support `resolv.conf`. And that's how it is designed. You can though put local `dnsmasq` and have that read your `resolv.conf` and then just point Nginx resolvers to that.
