### ISSUE TITLE
Improve variable naming

### ISSUE THREAD

**Issue by nielsole** [bungle/lua-resty-session#48]
This is not a bug report, but wishful thinking :)

I had extreme problems reading the code. A short comment for the most important methods would be useful. More importantly variable names could be a lot more helpful.
A lot of  variable names are reused for different meanings (`d` in the example) which makes it even harder to grasp the code.

Example:
https://github.com/bungle/lua-resty-session/blob/d006e524feb4d53880461c8c97bf8c7560a4b6c7/lib/resty/session.lua#L309-L315

What is the reason for the current naming? Performance improvements?

**Comment by bungle** [comment]
No reason. I liked tiny when I did that. That's it. I think you would hate this:
https://github.com/bungle/lua-resty-prettycjson/blob/master/lib/resty/prettycjson.lua

**Comment by nielsole** [comment]
yeah, I would ;) would you be open to a pull request with more significant naming, if I ever came to it during spare time?

**Comment by bungle** [comment]
@nielsole sure. I tend to also write more verbosely today.
