### ISSUE TITLE
session.id use ngx.say or ngx.log print ,but result garbled

### ISSUE THREAD

**Issue by giangithud** [bungle/lua-resty-session#50]
Hi,sorry to bother ; 
i want to get the session id, but the result i can't recognize, like this '󿾥l	3霫Ն', in nginx.conf i have already add 'charset utf8' ,my openResty version is '1.11.2.1'.
An question:can i use the session.id to identification the same user from explorer?
If you reply and give my question an answer ,i will grateful for this.

**Comment by bungle** [comment]
How about:
`ngx.say(ngx.encode_base64(session.id, true))`

**Comment by bungle** [comment]
Don't use `session.id` itself in your application. But store e.g. `user_id` in session:
```
local session_factory = require "resty.session"
local session = session_factory,start()
session.data.user_id = "james"
session:save()
```

**Comment by bungle** [comment]
Closing this. I will add `session.cookie.id` which returns `id` as what is in cookie itself.
