### ISSUE TITLE
Session lost upon redirection

### ISSUE THREAD

**Issue by tchimih** [bungle/lua-resty-session#52]
Hi there,

I am facing a problem right now. Herer is how I set my session:
`local session   = require "resty.session".start() `
`session.data.name = credentials.username \n`
`session:save()`

When I try to grab it from another page upon `ngx.redirect` I have a nil value for `session.data.name`

Here is how I try to grab it:

`local session   = require "resty.session".open()`
`ngx.say("<p> session.data.name  </p>")`
Thanks in advance.

**Comment by bungle** [comment]
@tchimih it definitely should not have problem with that.

**Comment by tchimih** [comment]
@bungle  I will try to reproduce the problem and come back to you with the outcome !

**Comment by bungle** [comment]
Do you have single nginx server with single server block where this redirection happens?

**Comment by bungle** [comment]
Also note this:
https://github.com/bungle/lua-resty-session#notes-about-turning-lua-code-cache-off

And are you using same client to do the redirection as the one that got the cookie?

**Comment by bungle** [comment]
please remember that:
```
ngx.redirect
```

will abort the light-thread, usually written as:

```
return ngx.redirect "..."
```
