### ISSUE TITLE
Advice: is there a way to display content of a encrypted session cookies for debugging?

### ISSUE THREAD

**Issue by thomasleplus** [bungle/lua-resty-session#53]
Hi,

I am trying to figure out an issue with my web application. I think the issue is that the wrong data is stored in the session so I was wondering if there is an easy way that I could inspect the content of my (encrypted) session cookie. I mean something like a command line that would receive as arguments the cookie(s) content and the session secret and display the content of the session?

Cheers,

Tom

**Comment by bungle** [comment]
@thomasleplus how about using:
https://github.com/bungle/lua-resty-session#none-cipher

**Comment by bungle** [comment]
Then it is just `base64decode(<data-part-of-the-session-cookie>)` and you will get JSON string.

**Comment by thomasleplus** [comment]
Good idea! Thanks.
