### ISSUE TITLE
Maybe session.secret should be 'required'

### ISSUE THREAD

**Issue by jpablo128** [bungle/lua-resty-session#55]
Hi Bungle, thanks a lot for all your work.
I ran into a problem and it took me a long time to figure it out, so I just want to document it in case somebody sees something similar.

Basically, the problem is that sessions don't work unless I explicitely set the 'secret' , **even though** I don't use lua_code_cache off;

In my setup, I have various nginx locations with content_by_lua_file <whatever.lua> and on those lua files I have:
  `local SESS = require "resty.session"`
so I can use the session functionality in my scripts.
On a login page, I set up a session:
```
local session = SESS.start({ name = "mysession" })
session.data.type = 'gui'
session.data.tenant_id = tenant_id
session:save()
```
On another script (actually in an access_by_lua_file) , I do check for the existence of a session, like so:
```
local SESS = require ('resty.session')
local session, present = SESS.open({ name = "mysession" })
if not session.present then
  return ngx.exit(ngx.HTTP_FORBIDDEN)
end
```
And this worked erratically... sometimes it worked (got the session established previously) but most of the time, the session was not detected (even though the cookie was there).
I debugged and I found that the 'problem' was in [this line](https://github.com/bungle/lua-resty-session/blob/master/lib/resty/session.lua#L288) : 
`if d and hmac(k, concat{ i, e, d, self.key }) == h then`

The second condition was always false. Even using
`cipher = "none"`
the problem was there.

I discovered that the secret was being generated on every request. This problem **is explained** in [the documentation here](https://github.com/bungle/lua-resty-session#notes-about-turning-lua-code-cache-off) , but since my app is NOT turning off the cache, I thought this didn't apply to me.

As soon as I created my sessions with a specific secret, and opened them with that secret, everything worked fine
`SESS.open({ name = "mysession" , secret = "mysecretwhateverblah" })`

I'm not really sure why the secret was being re-generated each time... even with cache "on" ... but my suggestion is to change the documentation to say that setting the 'secret' is not only a good idea...  but that it should **always** be done... more like a requirement.

**Comment by bungle** [comment]
Hi @jpablo128,

Can you check if the problem exists even if you run with single Nginx worker?

**Comment by bungle** [comment]
Also, try to add:
`require "resty.session"`

In `init_by_lua_block`. A place where you usually add `require "resty.core"`, and let us know if it made any difference?

**Comment by jpablo128** [comment]
Aapo,
Yes, those things you mentioned made a difference.
With only 1 worker, the problem disappears (that is, I don't need to explicitly specify a secret. The library works as intended).
If I use
`require "resty.session"`
in my `init_by_lua_block`, the problem dissapears too... even with more than 1 worker.
I hope that info helps you.
Thanks.

**Comment by bungle** [comment]
@jpablo128 ok, great!

**Comment by bungle** [comment]
I don't think there is easy way to solve the `secret` issue with the library itself. So work-arounds above are what we would recommend, or use `shm` session storage or perhaps even some other server side storage. Or just specify secret or on single node load session library once on init_by_lua.
