### ISSUE TITLE
Is it needed/Is there a way to rotate/renew server secret, except restarting nginx ?

### ISSUE THREAD

**Issue by yw662** [bungle/lua-resty-session#56]
If the server need to run for a long time without restarting, server secret will need to be renewed periodically.
So, will lua-resty-session do it automatically, or does it provide a  way to do that ?

**Comment by bungle** [comment]
@yw662,

At the moment it does not support secret rotation, or multiple secrets at same time.

**Comment by bungle** [comment]
The new version 4.0.0 has options for secret rotation (aka fallback secrets)
