### ISSUE TITLE
Race condition when setting session state

### ISSUE THREAD

**Issue by andreasBerre** [bungle/lua-resty-session#57]
We're using lua-resty-openidc in a clustered environment (multiple ingress servers), using a single redis as a session store. 

We're experiencing a problem where a race condition occurs when multiple requests are made simultaneously after the access token has expired: both requests will trigger a refresh, obtain a new access token, and store the token to the redis session. Storing the session updates the hmac section of the session cookie, and sets a new session cookie on the response. 

The problem seems to be that the request which is last to set the session access-token is not always the last to return the response with the new session cookie, which means that the hmac section in the client side cookie does not correspond with the cookie from the redis session store on the following requests, causing 401 errors.

Is there a good way to resolve this?

Relevant code-section (decrypt returns null): https://github.com/bungle/lua-resty-session/blob/4429a06ffac1724a056fafa954c0394d437b261f/lib/resty/session.lua#L287

###### Environment
- lua-resty-session: 2.22-1
- lua:  5.1.5

###### Configuration
```
 set $session_secret <secret>;

  set $session_cookie_renew 900;
  set $session_check_ssi         off;

  set $session_storage redis;

  set $session_redis_prefix        sessions;
  set $session_redis_host          redis-master.${OPENSHIFT_NAMESPACE}.svc.cluster.local;
  set $session_redis_port          6379;
  set $session_redis_auth          ${REDIS_PASSWORD};
  set $session_redis_uselocking    on;
  set $session_redis_spinlockwait  10000;
  set $session_redis_maxlockwait   30;
  set $session_redis_pool_timeout  45;
  set $session_redis_pool_size     10;

  set $session_cookie_samesite off;
```

**Comment by zandbelt** [comment]
you are aware of this: https://github.com/zmartzone/lua-resty-openidc/issues/190 ?

**Comment by andreasBerre** [comment]
No, that escaped my attention. Upgraded to latest openidc, we're now getting a new session for every refresh, which solves the problem. 

Thanks for your help & sorry for the duplicate.

**Comment by zandbelt** [comment]
np, thanks for the quick turn-around

**Comment by bungle** [comment]
@zandbelt thanks a lot! :-)
