### ISSUE TITLE
error log product by example

### ISSUE THREAD

**Issue by stlnkm** [bungle/lua-resty-session#62]
Hi!
I use docker compose contains 3 services: a openresty naming app, a mysql service naming db, and a redis service naming redis. Part of nginx config below:
![image](https://user-images.githubusercontent.com/1908920/53897088-58181980-4070-11e9-81fe-3bcb9b2d2666.png)

And I run the /start location, and found a error in the nginx's error log file:
![image](https://user-images.githubusercontent.com/1908920/53897326-deccf680-4070-11e9-8b25-e40bb87d1cf7.png)

How can I fix it? Thx!

**Comment by bungle** [comment]
Can your Nginx resolve `redis`? How have you setup your resolvers? Remember Nginx doesn't use system resolver.

**Comment by stlnkm** [comment]
Yes, I have setup resolver: resolver 127.0.0.11 valid=30s local=on;
Everything goes well except leaving an error log, when directive lua_socket_log_errors on.
