### ISSUE TITLE
Support for ngx-distributed-shm

### ISSUE THREAD

**Issue by grrolland** [bungle/lua-resty-session#68]
Hello,

I wrote a module storage for lua-resty-session based on Vertx and Hazelcast Libraries. It works like a memcached backend but with the following advantages ; 
  -  Simple cluster with only two replicated members
  -  Support atomic distributed locking with higher performance than Memcache or Redis

Are you interrested to include this storage module in you project ?

Here is the link to the github project : https://github.com/grrolland/ngx-distributed-shm

Regards,
Grégoire Rolland

**Comment by bungle** [comment]
This is merged now, @grrolland thank you very much!
