### ISSUE TITLE
Sometimes decryption fails

### ISSUE THREAD

**Issue by vladimir-smirnov-sociomantic** [bungle/lua-resty-session#7]
It seems for me, that sometimes encryption fails.

The best way to reproduce is to try access Nagios and use nginx's oauth plugin: https://github.com/vladimir-smirnov-sociomantic/nginx-oauth-on-dotcloud (mine fork, because not all changes are merged for now).

With debug log I've found that sometimes I receive data from redis/cookies, but they fail to decrypt

**Comment by Devrandomuser** [comment]
> I think that we might need to implement locking in the session library as well (I'm not sure though if this is needed for client side sessions as well - probably only in that case when you want to insert a few iframes on a page that is served by some other site[...]).


@bungle 
Please implement a function to use a lock, otherwise race conditions are hard to debug / find.
-Turning off locks by default would be the best from my point of view.
