### ISSUE TITLE
Data encryption weakness

### ISSUE THREAD

**Issue by supereldar** [bungle/lua-resty-session#71]
Hi!
Thank you very much for lua-resty-session module, it's very convenient and easy to use.
I've researched it's source code and found a couple of interesting stuff which you may consider as a deviation from desired design or even as a security weakness. Anyway, I'm interested and look forward to your comments.

In file '/strategies/default.lua' default.save function encrypt data part with following call "self.cipher:encrypt(d, k, i, self.key)". --line 12
Function cipher:encrypt from '/ciphers/aes.lua' expect only 3 parameters, so self.key variable (which is fourth) is being ignored. if you wanted self.key to somehow participate in data encryption then this is not happening.
Encryption key which is k variable for the encryption function I mentioned ahead is hmac_sha1 result from line 9 of same file
local k = self.hmac(self.secret, i .. e) 
It's mean that k will always be 160bit long while encryption algo use aes with 256 bits key size on defaults. The code is working because of encryption function which probably adds extra zeros to the passed key to make it compatible with the algorithm. But in fact, this behaviour loosens robustness. I think it would be a good idea to convert self.key to 96 bits long string and concat with a current k value for sticking key with user or make k = self.secret for unleashing full power of aes256

**Comment by bungle** [comment]
@supereldar, yes, that `self.key` is excess code, I'll remove that.

The `lua-resty-aes` generates key from that `hmac_sha1` hash (with another hash function to get right length):
https://github.com/openresty/lua-resty-string/blob/master/lib/resty/aes.lua#L135

Sure we can improve.

**Comment by bungle** [comment]
The forth parameter:
```
string adapter:encrypt(data, key, iv or salt, associated data)
```

is there for associated data, which some AES-modes (that are currently not supported may use).

**Comment by bungle** [comment]
closing this as it is not really an issue.
