### ISSUE TITLE
Support for SSL Redis connections

### ISSUE THREAD

**Issue by akuma12** [bungle/lua-resty-session#73]
Hi! Thank you for this wonderful module!

[lua-resty-redis](https://github.com/openresty/lua-resty-redis) recently updated to support SSL connections and SSL verification. Are there any plans to update lua-resty-session/lib/resty/session/storage/redis.lua to enable those features? If not, I would be happy to make this update.

Thanks!

**Comment by Tieske** [comment]
@akuma12 some 👀 on #75 would be nice 😄
