### ISSUE TITLE
Possible to update a save an updated cookie without updating expiration time?

### ISSUE THREAD

**Issue by ProbablyRusty** [bungle/lua-resty-session#80]
Is it possible to update data for a session from a cookie sent in with the request and save back the updated cookie in the response _without_ updating the existing expiration time?

So that something like this would result in saving a new cookie with a new name but the same expiration time as the cookie sent in the request:

```lua
              local session = require "resty.session".open()
              if ( session.present and session.data.name == "foo" )
              then
                    session:start()
                    session.data.name = "bar"
                    session:save()
              end
```

**Comment by bungle** [comment]
@ProbablyRusty at the moment no. PR is welcomed.

**Comment by bungle** [comment]
With version 4.0.0 each save results a new session id and cookie, there is absolute_timeout which is carried over the saves. I am closing this. @ProbablyRusty if you care to elaborate what is your use case, it would help to understand this better.
