### ISSUE TITLE
 entry thread aborted: runtime error: /usr/share/lua/5.1/resty/session.lua:20: module 'resty.random' not found

### ISSUE THREAD

**Issue by moidroid** [bungle/lua-resty-session#93]
Hello,
Beginners question.
Trying to get Nginx compiled with LUA and running into a problem with missing LUA package.
In which package can I find resty.random?

I have tried to search in luarocks for it but cannot really see which one it would be.

I am using LUA 5.1

**Comment by bungle** [comment]
It comes with:
https://github.com/openresty/lua-resty-string
See: https://github.com/openresty/lua-resty-string/blob/master/lib/resty/random.lua

Should be packaged with OpenResty automatically. I am closeing this.

**Comment by bungle** [comment]
There is this version on luarocks:
https://luarocks.org/modules/rsander/lua-resty-string

**Comment by bungle** [comment]
You can also use `opm`: https://opm.openresty.org/
