### ISSUE TITLE
Civetweb integration

### ISSUE THREAD

**Issue by veselinovicst** [bungle/lua-resty-session#94]
Hello, is it possible to integrate this library into civetweb server and use it for simple token based authentication ?

**Comment by bungle** [comment]
@veselinovicst, I have been asked it before, e.g. to add support for Envoy and now to CivetWeb. I think the library could be modularized to support those. I just have not had time to look at it. On source code you probably want to look for `ngx.xxx` and perhaps some external libs like `require "resty.xxx"`, and those may be needed to be replaced with something that works with CivitWeb.

**Comment by zandbelt** [comment]
I have a prototype change for this "web server modularization" that I hope to be able to send as a PR in a few weeks/months from now. I need to update it from version 2 to version 3 of lua-resty-session.

**Comment by veselinovicst** [comment]
Hey, thank you for the response. I decided to implement session management myself.
